
# Secret key base is created on deployment server and loaded here.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: "uuddlrlrabsse"

test:
  secret_key_base: 'secretkeybase'
